server:
  port: 7402
  servlet:
    context-path: /o2o-ds-inner-api

spring.profiles.active: dev

log:
  show: true

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://112.124.12.104:3306/demo?useUnicode=true&autoReconnect=true&useServerPrepStmts=true&useSSL=true
    username: root
    password: Aa8711591
    druid:
      test-on-borrow: false
      test-while-idle: false
      test-on-return: false
      validation-query: SELECT 1
      max-active: 4
      initial-size: 4
      max-wait: 3000
      min-idle: 3
      time-between-eviction-runs-millis: 3000
      min-evictable-idle-time-millis: 300000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
  redis:
    host: 127.0.0.1
    hostName: ${spring.redis.host}
    port: 6379
    password:
    database: 1
    pool:
      # 控制一个pool可分配多少个jedis实例
      max-active: -1
      # 最大活动对象数
      max-total: 1000
      # 最大能够保持idel状态的连接数
      max-idle: 100
      # 最小能够保持idel状态的连接数
      min-idle: 10
      # 当池内没有返回对象时，最大等待时间
      max-wait-millis: 10000
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
workerId: 1
centerId: 1

swagger:
  production: false


xxl:
  job:
    admin:
      addresses: http://112.124.12.104:8970/xxl-job-admin
      accessToken: linhanghuidashuaibi
    executor:
      appname: demo-job-dev
      logpath: /data/logs/java/demo-job
      logretentiondays: -1
      port: 8970